BulletinBoard/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

app_name = 'BulletinBoard'
urlpatterns = [
    path('kawaoka/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('EventSchedule/', include('EventSchedule.urls')),
    path('Documents/', include('Documents.urls')),
    path('CirculationBoard/', include('CirculationBoard.urls')),
]
urlpatterns += staticfiles_urlpatterns()

CirculationBoard/urls.py
from django.urls import path

from . import views

app_name = 'CirculationBoard'
urlpatterns = [
    path(
        'CirculationBoard/',
        views.all_circulation_board,
        name='AllCirculationBoard'
    ),
    path(
        '<int:pk>/',
        views.CirculationBoardDetailView.as_view(),
        name="CirculationBoardDetail"
    ),
]

Documents/urls.py
from django.urls import path

from . import views

app_name = 'Documents'
urlpatterns = [
    path('AllDocumentList/', views.all_document_list, name='AllDocumentList'),
    path('<int:pk>/', views.DocumentDetailView.as_view(), name='DocumentDetail'),
]

EventSchedule/urls.py
from django.urls import path

from . import views

app_name = 'EventSchedule'
urlpatterns = [
    path(
        "AllEventSchedule/",
        views.all_event_schedule,
        name="AllEventSchedule"
    ),
    path(
        "<int:pk>/",
        views.DetailView.as_view(),
        name="EventDetail"
    ),
]

CirculationBoard/models.py
from django.db import models


class CirculationBoard(models.Model):
    # タイトル
    title = models.CharField('Title', max_length=200)
    # 開始日
    start_date = models.DateField('Start Date')
    # 回収日
    end_date = models.DateField('End Date', null=True, blank=True)

    def __str__(self):
        return self.title

Documents/models.py
import os
from django.db import models
from django.core.validators import FileExtensionValidator

from CirculationBoard.models import CirculationBoard


class Document(models.Model):
    # 文書名
    document_name = models.CharField('Document Name', max_length=200)
    # 掲載日
    upload_date = models.DateField('Upload Date')
    # 文書ファイル(PDF)
    document_file = models.FileField(
        'Document File',
        upload_to='documents/%Y',
        validators=[FileExtensionValidator(['pdf'])],
        null=True,
        blank=True
    )
    # 備考
    remarks_text = models.TextField(
        'Remarks',
        max_length=1000,
        null=True,
        blank=True
    )
    # 回覧板
    circulation_board = models.ForeignKey(
        CirculationBoard,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.document_name

    def file_name_only(self):
        name = os.path.basename(self.document_file.name)
        name = os.path.splitext(name)[0]
        return name

EventSchedule/models.py
from django.db import models


class EventSchedule(models.Model):
    # イベント名
    event_name = models.CharField('Event Name', max_length=100)
    # 場所(集合場所)
    place = models.CharField('Place', max_length=100)
    # 対象者
    target_person = models.CharField(
        'Target',
        max_length=100,
        null=True,
        blank=True
    )
    # 詳細情報
    detail_info = models.TextField(
        'Detail',
        max_length=1000,
        null=True,
        blank=True
    )
    # 予定日
    schedule_daytime = models.DateTimeField('Schedule')
    # 予備日
    preparation_daytime = models.DateTimeField(
        'Preparation',
        null=True,
        blank=True
    )
    # 実施日
    implementation_datetime = models.DateTimeField(
        'Implemantation',
        null=True,
        blank=True
    )
    # 備考
    remarks = models.TextField(
        'Remark',
        max_length=1000,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.event_name

BulletinBoard/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone

from EventSchedule.models import EventSchedule
from CirculationBoard.models import CirculationBoard
from Documents.models import Document


def index(request):
    # Get date & time.
    today = timezone.now()

    # Get event schedule (most recent 5)
    first_event = EventSchedule.objects.filter(schedule_daytime__gt=today).\
        order_by('schedule_daytime').first()
    event_list = EventSchedule.objects.filter(schedule_daytime__gt=today).\
        order_by('schedule_daytime')[1:5]

    # Get document list (most recent 5)
    document_list = Document.objects.filter(upload_date__lte=today).\
        order_by('-upload_date')[:5]

    # Get circuration board (most recent 5)
    circulating_list = CirculationBoard.objects.filter(end_date__isnull=True).\
        order_by('start_date')[:5]

    # Rendering page
    context = {
        'firstevent': first_event,
        'eventlist': event_list,
        'documentlist': document_list,
        'circulatinglist': circulating_list,
    }
    return render(request, 'BulletinBoard/index.html', context)

CirculationBoard/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import DetailView

from .models import CirculationBoard


def all_circulation_board(request):
    year_of_first_day = timezone.datetime(2022, 4, 1)
    year_of_last_day = timezone.datetime(2023, 3, 31)
    circulationlist = CirculationBoard.objects.filter(
            start_date__gte=year_of_first_day,
            end_date__lte=year_of_last_day
        ).order_by('start_date')
    context = {
        'circulationlist': circulationlist,
    }
    return render(request, 'CirculationBoard/CirculatedList.html', context)

class CirculationBoardDetailView(DetailView):
    model = CirculationBoard
    template_name = "CirculationBoard/CirculationBoardDetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        document_list = context.get("object")
        document_list = document_list.document_set.all()
        context["document_list"] = document_list
        return context

Documents/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import DetailView

from .models import Document


def all_document_list(request):
    year_of_first_day = timezone.datetime(2022, 4, 1)
    year_of_last_day = timezone.datetime(2023, 3, 31)
    document_list = Document.objects.filter(
        upload_date__gte=year_of_first_day,
        upload_date__lte=year_of_last_day).order_by('upload_date')
    context = {
        'documentlist': document_list,
    }
    return render(request, 'Documents/AllDocuments.html', context)


class DocumentDetailView(DetailView):
    model = Document
    template_name = 'Documents/DocumentDetail.html'

EventSchedule/views.py
import datetime

from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views.generic import DetailView

from .models import EventSchedule


def all_event_schedule(request):
    next_year_first_day = datetime.datetime(2023, 4, 1, tzinfo=timezone.utc)
    eventlist = EventSchedule.objects.filter(
        schedule_daytime__lt=next_year_first_day).order_by('schedule_daytime')
    context = {
        "eventlist": eventlist,
    }
    return render(request, "EventSchedule/AllEventSchedule.html", context)


class DetailView(DetailView):
    model = EventSchedule
    template_name = 'EventSchedule/EventDetail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        detail_data = context.get("object")
        detail_data = str(detail_data.detail_info).splitlines()
        context["detail_info"] = detail_data
        return context

templates/BulletinBoard/index.html
<!DOCTYPE html>

{% extends 'base_bulletinboard.html' %}
{% load bootstrap_icons %}

{% block header_message %}
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom align-items-center">
        <div class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none fs-1 fw-bold">
            {% bs_icon 'house-heart' size='1.0em' %}
            <span>川田・岡ノ山 掲示板</span>
        </div>
        <ul class="nav nav-pills md-3" id="indexTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">ホーム</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="event-tab" data-bs-toggle="tab" data-bs-target="#event-tab-pane" type="button" role="tab" aria-controls="event-tab-pane" aria-selected="false">イベント</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="documents-tab" data-bs-toggle="tab" data-bs-target="#documents-tab-pane" type="button" role="tab" aria-controls="documents-tab-pane" aria-selected="false">資料</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="c-board-tab" data-bs-toggle="tab" data-bs-target="#c-board-tab-pane" type="button" role="tab" aria-controls="c-board-tab-pane" aria-selected="false">回覧板</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="about-tab" data-bs-toggle="tab" data-bs-target="#about-tab-pane" type="button" role="tab" aria-controls="about-tab-pane" aria-selected="false">当サイトについて</button>
            </li>
        </ul>
    </header>
{% endblock %}

{% block main_contents %}
    <div class='container tab-content'>
        <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledbody="home-tab" tabindex="0">
            <div class='row'>
                <div class='col-3'></div>
                <div class='fs-2 fw-bold col-6 d-flex align-items-center justify-content-center'>最新情報</div>
                <div class='col-3'></div>
            </div>
            <div class='row'>
                <div class='col-3'></div>
                <div class='fs-4 col-6 d-flex align-items-center justify-content-center'>2022年 6月 2日 更新</div>
                <div class='col-3'></div>
            </div>
            <hr>
            <div class='row'>
                <div class='col-3'></div>
                <div class='fs-2 col-6 d-flex align-items-center justify-content-center'>
                    <ul class='fs-4'>
                        <li>資料を3件追加しました。</li>
                    </ul>
                </div>
                <div class='col-3'></div>
            </div>
        </div>
        <div class="tab-pane fade show" id="event-tab-pane" role="tabpanel" aria-labelledbody="event-tab" tabindex="0">
            <p class='fs-2 fw-bold text-center'>行事予定</p>
            {% if eventlist %}
            <p class='fs-4 text-center'>直近の{{ eventlist.count|add:1 }}件を表示しています。</p>
            <table class='table table-striped table-bordered text-center'>
                <thead>
                    <tr>
                        <th>行事名</th>
                        <th>場所</th>
                        <th>日付</th>
                        <th>時刻</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class='table-primary'>
                        <td scope="row"><a href={% url "EventSchedule:EventDetail" firstevent.id %}>{{ firstevent.event_name }}</a></td>
                        <td>{{ firstevent.place }}</td>
                        <td><span class='text-nowrap'>{{ firstevent.schedule_daytime | date:'Y年' }}</span><span  class='text-nowrap'>{{ firstevent.schedule_daytime | date:'n月j日' }}</span></td>
                        <td>{{ firstevent.schedule_daytime | date:'G:i' }}</td>
                    </tr>
                    {% for event in eventlist %}
                    <tr>
                        <td scope="row"><a href="{% url 'EventSchedule:EventDetail' event.id %}">{{ event.event_name }}</a></td>
                        <td>{{ event.place }}</td>
                        <td><span class='text-nowrap'>{{ event.schedule_daytime | date:'Y年' }}</span><span  class='text-nowrap'>{{ event.schedule_daytime | date:'n月j日' }}</span></td>
                        <td>{{ event.schedule_daytime | date:'G:i' }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class='fs-5 text-center'>年度行事一覧は<a href={% url 'EventSchedule:AllEventSchedule' %}>こちら</a>。</p>
            {% else %}
            <p class='fs-4 text-center'>予定された行事はありません</p>
            {% endif %}
        </div>
        <div class="tab-pane fade show" id="documents-tab-pane" role="tabpanel" aria-labelledbody="documents-tab" tabindex="0">
            <p class='fs-2 fw-bold text-center'>資料</p>
            {% if documentlist %}
            <div class='fs-6 text-center'>
                <span class='text-nowrap'>回覧済み資料を公開しています。</span>
                <span class='text-nowrap'>一部資料は諸事情により掲載をしていません。</span>
            </div>
            <br>
            <p class='fs-4 text-center'>以下は、直近の{{ documentlist.count }}件を表示しています。</p>
            <table class='table table-striped table-bordered text-center'>
                <thead>
                    <tr>
                        <th>資料名</th>
                        <th>掲載日</th>
                    </tr>
                </thead>
                <tbody>
                    {% for document in documentlist %}
                    <tr>
                        <td scope="row"><a href={% url 'Documents:DocumentDetail' document.id %}>{{ document.document_name }}</a></td>
                        <td>{{ document.upload_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class='fs-4 text-center'>掲載資料はありません。</p>
            {% endif %}
            <p class='fs-5 text-center'>全ての資料は<a href={% url 'Documents:AllDocumentList' %}>こちら</a>。</p>
        </div>
        <div class="tab-pane fade show" id="c-board-tab-pane" role="tabpanel" aria-labelledbody="c-board-tab" tabindex="0">
            <p class='fs-2 fw-bold text-center'>回覧状況</p>
            {% if circulatinglist %}
            <p class='fs-4 text-center'>直近の{{ circulatinglist.count }}件を表示しています。</p>
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th>タイトル</th>
                        <th>開始日</th>
                    </tr>
                </thead>
                <tbody>
                    {% for board in circulatinglist %}
                    <tr>
                        <td scope="row">{{ board.title }}</td>
                        <td>{{ board.start_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class='fs-4 text-center'>現在回覧中の回覧板はありません。</p>
            {% endif %}
            <p class='fs-5 text-center'>過去の回覧は<a href={% url 'CirculationBoard:AllCirculationBoard' %}>こちら</a>。</p>
        </div>
        <div class="tab-pane fade show" id="about-tab-pane" role="tabpanel" aria-labelledbody="about-tab" tabindex="0">
            <div class="row">
                <div class="col-2">
                </div>
                <div class="col-8">
                    当サイトでは、
                    <ul>
                        <li>今後の行事予定</li>
                        <li>回覧板の回覧状況</li>
                        <li>回覧済み資料</li>
                    </ul>
                    を公開しています。
                </div>
                <div class="col-2">
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-2">
                </div>
                <div class="col-8">
                    <ul>
                        <li>こんな機能が欲しい。</li>
                        <li>こんな事はできる？</li>
                        <li>この画面が見難い。</li>
                    </ul>
                    <div>など、サイトに関するご意見・ご要望は、</div>
                    <div><a href="mailto:mookouchi.biz.r01@gmail.com">川田 大河内正博</a>まで、ご連絡ください。</div>
                </div>
                <div class="col-2">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/CirculationBoard/CirculatedList.html
<!DOCTYPE html>

{% extends 'base_bulletinboard.html' %}

{% block header_message %}
<header>
    <p class='fs-1 text-center'>川田・岡ノ山　回覧状況</p>
    <p class='fs-3 text-center'></h3>
</header>
{% endblock %}

{% block main_contents %}
<table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
        </tr>
    </thead>
    <tbody>
        {% for board in circulationlist %}
        <tr>
            <td scope="row"><a href="{% url 'CirculationBoard:CirculationBoardDetail' board.id %}">{{ board.title }}</a></td>
            <td>{{ board.start_date | date:'Y年n月j日' }}</td>
            <td>{{ board.end_date | date:'Y年n月j日' }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class='text-center'>
    <a href={% url 'index' %}>戻る</a>
</div>
{% endblock %}

templates/CirculationBoard/CirculationBoardDetail.html
{% extends "base_bulletinboard.html" %}

{% block header_message %}
    <header class='text-center'>
        <p class='fs-1 fw-bold'>{{ object }}</p>
    </header>
{% endblock %}

{% block main_contents %}
    <div class='text-center'>
        <p class='fs-3 fw-bold'>開始日</p>
        <p class='fs-4'>{{ object.start_date }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>終了日</p>
        <p class='fs-4'>{{ object.end_date }}</p>
    </div>
    <br>
    <div class='row justify-align-center'>
        <p class='fs-3 fw-bold text-center'>資料一覧</p>
        <ul class='list-group'>
            {% for document in document_list %}
            <li class='list-group-item fs-4 text-center'><a href='{% url "Documents:DocumentDetail" document.id %}'>{{ document }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/Documents/AllDocuments.html
<!DOCTYPE html>

{% extends 'base_bulletinboard.html' %}

{% block header_message %}
<header>
    <p class='fs-1 text-center'>川田・岡ノ山　資料一覧</p>
    <p class='fs-3 text-center'></h3>
</header>
{% endblock %}

{% block main_contents %}
<table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>掲載日</th>
        </tr>
    </thead>
    <tbody>
        {% for document in documentlist %}
        <tr>
            <td scope="row"><a href={% url 'Documents:DocumentDetail' document.id %}>{{ document.document_name }}</a></td>
            <td>{{ document.upload_date | date:'Y年n月j日' }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class='text-center'>
    <a href={% url 'index' %}>戻る</a>
</div>
{% endblock %}

templates/Documents/DocumentDetail.html
{% extends "base_bulletinboard.html" %}

{% block header_message %}
    <header class='text-center'>
        <p class='fs-1 fw-bold'>{{ object }}</p>
    </header>
{% endblock %}

{% block main_contents %}
    <div class='text-center'>
        <p class='fs-3 fw-bold'>掲載日</p>
        <p class='fs-4'>{{ object.upload_date }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>ファイル</p>
        <p class='fs-4'><a href='{{ MEDIA_URL }}{{ object.document_file.name }}'>{{ object.file_name_only }}</a></p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>備考</p>
        <p class='fs-4'>{{ object.remarks_text }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>回覧板</p>
        <p class='fs-4'>{{ object.circulation_board.title }}</p>
    </div>
{% endblock %}

templates/EventSchedule/AllEventSchedule.html
<!DOCTYPE html>

{% extends 'base_bulletinboard.html' %}

{% block header_message %}
<header>
    <p class='text-center fs-2 fw-bold'>小島町／川田・岡ノ山　行事一覧</p>
    <p class='text-center'></p>
</header>
{% endblock %}

{% block main_contents %}
<table class='table table-striped text-center table-bordered'>
    <thead>
        <tr>
            <th>行事名</th>
            <th>場所</th>
            <th>日付</th>
            <th>時刻</th>
        </tr>
    </thead>
    <tbody>
        {% for event in eventlist %}
        <tr>
            <td scope="row"><a href="{% url 'EventSchedule:EventDetail' event.id %}">{{ event.event_name }}</a></td>
            <td>{{ event.place }}</td>
            <td>{{ event.schedule_daytime | date:'Y年n月j日' }}</td>
            <td>{{ event.schedule_daytime | date:'G:i' }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class='text-center'>
    <a href={% url 'index' %}>戻る</a>
</div>
{% endblock %}

templates/EventSchedule/EventDetail.html
{% extends "base_bulletinboard.html" %}

{% block header_message %}
    <header class='text-center'>
        <p class='fs-1 fw-bold'>{{ object }}</p>
    </header>
{% endblock %}

{% block main_contents %}
    <div class='text-center'>
        <p class='fs-3 fw-bold'>日時</p>
        <p class='fs-4'>{{ object.schedule_daytime }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>場所</p>
        <p class='fs-4'>{{ object.place }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>詳細</p>
        <div class='text-left'>
            {% for line in detail_info %}
            <p class='fs-4'>{{ line }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/EventSchedule/EventSchedule.html
{% block eventSchedule %}
<table class='table table-striped text-center' border='1' >
    <thead>
        <tr>
            <th>行事名</th>
            <th>場所</th>
            <th>日付</th>
            <th>時刻</th>
        </tr>
    </thead>
    <tbody>
        {% for event in eventlist %}
        <tr>
            <td scope="row">{{ event.event_name }}</td>
            <td>{{ event.place }}</td>
            <td>{{ event.schedule_daytime | date:'Y年n月j日' }}</td>
            <td>{{ event.schedule_daytime | date:'G:i' }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/EventSchedule/eventdetail.html
{% extends "base_bulletinboard.html" %}

{% block header_message %}
    <header class='text-center'>
        <p class='fs-1 fw-bold'>{{ object }}</p>
    </header>
{% endblock %}

{% block main_contents %}
    <div class='text-center'>
        <p class='fs-3 fw-bold'>日時</p>
        <p class='fs-4'>{{ object.schedule_daytime }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>場所</p>
        <p class='fs-4'>{{ object.place }}</p>
    </div>
    <br>
    <div class='text-center'>
        <p class='fs-3 fw-bold'>詳細</p>
        <div class='text-left'>
            {% for line in detail_info %}
            <p class='fs-4'>{{ line }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load django_bootstrap5 %}

<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    
    <title>川田・岡ノ山 掲示板</title>
</head>
    <body>
        {% block header_message %}
        {% endblock %}

        {% block main_contents %}
        {% endblock %}

        <footer style='background-color:gray' align='right'>
            <div>Maintenance by Masahiro Ookouchi.</div>
            <div>Powered by Python3, Django4, Bootstrap5.</div>
        </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@popperjs/core@2" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>  </body>
</html>

templates/base_bulletinboard.html
<!DOCTYPE html>

{% load django_bootstrap5 %}

<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    
    <title>川田・岡ノ山 掲示板</title>
</head>
    <body>
        <div class='container bg-white bg-gradient text-dark'>
        {% block header_message %}
        {% endblock %}
        </div>

        <div class=container>
        {% block main_contents %}
        {% endblock %}
        </div>

        <footer class='bg-secondary text-end'>
            <div>Maintenance by Masahiro Ookouchi .</div>
            <div>Privided by Conoha VPS .</div>
            <div>Powered by Python3.10.4, Django4.0.3, Bootstrap5, gunicorn20.0.1 .</div>
        </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    -->
</body>
</html>